### ISSUE TITLE
How can I set up a rest endpoint without using socket.io?

### ISSUE THREAD

**Issue by yasinAtlibra** [andersonba/yve-bot#10]
It would be great if you provide an example of restifying the bot.

**Comment by yasinAtlibra** [comment]
I tried the following

const rules = `

- Hello! I'm Yve Bot.

`;

const YveBot = require("yve-bot");
const bot = new YveBot(rules);
got the error below.

      n.map is not a function

how can I fix this?

**Comment by andersonba** [comment]
Sure! I will do it 👍

**Comment by andersonba** [comment]
@yasinAtlibra Did you check the `web` example?
You can define the rules using javascript or converting a yaml string (js-yaml), no need server.
If you want to save the user's answers in a database, you can just call the API using the bot events, like `end` or `storeChanged`.
```javascript
new YveBot(rules)
  .on('end', (data) => {
    $.post('url', { data });
  })
  ...
```

But if you want to load the chat rules in server and keep the control of rules/sessions, step by step, like
```
User opens chat
  Client ask server for rule
    Server replies a rule
      Client answers
        Server receives and replies the next rule
          ... 
```
I recommend you to use socket.io because the chat conversation is async, you will need to implement sequential ajax requests to simulate the same behavior.

Which kind you're talking about?

**Comment by yasinAtlibra** [comment]
Thanks for your answer, I been able to run the bot, but did not use rest point. Just followed your example 👍
